### ISSUE TITLE
Trying to use 8.2 has some sort of apt issue with unicode?

### ISSUE THREAD

**Issue by purdy** [nanasess/setup-php#275]
This was the output when I tried recently:

```
Run nanasess/setup-php@v4
  with:
    php-version: 8.2
  env:
    CI_ENVIRONMENT: testing
Installing PHP 8.2
Installing PHP 8.2.20
hasPatchVersion(8.2): false
hasAptVersion(8.2): true
Installing PHP 8.2 via apt
/home/runner/work/_actions/nanasess/setup-php/v4/lib/apt-install-php-ubuntu.sh 8.2
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:6 https://packages.microsoft.com/repos/azure-cli jammy InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3632 B]
Get:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1734 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [319 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1997 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [339 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1087 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [251 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [43.3 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [10.8 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1526 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [261 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1937 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [330 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [860 kB]
Get:21 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [167 kB]
Get:22 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [13.7 kB]
Get:23 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [39.1 kB]
Get:24 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [159 kB]
Fetched 11.3 MB in 2s (5759 kB/s)
Reading package lists...
PPA publishes dbgsym, you may need to include 'main/debug' component
Repository: 'deb https://ppa.launchpadcontent.net/ondrej/php/ubuntu/ jammy main'
Description:
Co-installable PHP versions: PHP 5.6, PHP 7.x, PHP 8.x and most requested extensions are included. Only Supported Ubuntu Releases (https://wiki.ubuntu.com/Releases) are provided.

Debian oldstable and stable packages are provided as well: https://deb.sury.org/#debian-dpa

You can get more information about the packages at https://deb.sury.org/

BUGS&FEATURES: This PPA now has a issue tracker:
https://deb.sury.org/#bug-reporting

CAVEATS:
1. If you are using php-gearman, you need to add ppa:ondrej/pkg-gearman
2. If you are using apache2, you are advised to add ppa:ondrej/apache2
3. If you are using nginx, you are advised to add ppa:ondrej/nginx-mainline
   or ppa:ondrej/nginx

PLEASE READ: If you like my work and want to give me a little motivation, please consider donating regularly: https://donate.sury.org/

WARNING: add-apt-repository is broken with non-UTF-8 locales, see
https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

# LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
More info: https://launchpad.net/~ondrej/+archive/ubuntu/php
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/ondrej-ubuntu-php-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/ondrej-ubuntu-php-jammy.list
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 357, in main
    shortcut.add()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 222, in add
    self.add_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 398, in add_key
    if not all((self.trustedparts_file, self.trustedparts_content)):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 141, in trustedparts_content
    key = self.lpppa.getSigningKeyData()
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 592, in __call__
    response, content = self.root._browser._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 429, in _request
    raise error
lazr.restfulclient.errors.ServerError: HTTP Error 500: Internal Server Error
Response headers:
---
connection: close
content-length: 30
content-type: text/plain;charset=utf-8
date: Thu, 20 Jun 2024 13:33:21 GMT
server: gunicorn
status: 500
x-lazr-oopsid: OOPS-e113301ff17b4d85c253bb5ef118416a
x-powered-by: Zope (www.zope.org), Python (www.python.org)
x-request-id: 12f3e3bc-f872-42a9-b21f-5386fc863f0a
x-vcs-revision: bbfa2351d9d6a9ddfe262109428f7bf5516e65d1
---
Response body:
---
b'GPGKeyTemporarilyNotFoundError'
---
```

**Comment by nanasess** [comment]
@purdy This is a lunchpad.net error, please take a moment and try again.
